In [22]:
import numpy as np
import torch

t = torch.tensor([[1, 2], [3, 4]])
t = torch.tensor([[1, 2], [3, 4]], device="cuda:0")
t = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
t = torch.arange(0, 10)

# 以下３つ同じ動作
t = torch.zeros(100, 10).to("cuda:0")
t = torch.zeros(100, 10).cuda()
t = torch.zeros(100, 10).to("cuda")

t = torch.randn(100, 10)
t.size()

torch.Size([100, 10])

In [23]:
t = torch.tensor([[1, 2], [3, 4]])
x = t.numpy()

t = torch.tensor([[1, 2], [3, 4]]).cuda()
x = t.to("cpu").numpy()

In [36]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])

print("t[0, 2]:\n", t[0, 2])
print("t[:, :2]:\n", t[:, :2])
print("t[:, [1, 2]]:\n", t[:, [1, 2]])
print("t[t > 3]:\n", t[t>3])
t[0, 1] = 100
print("t[0, 1] = 100:\n", t)
t[:, 1] = 200
print("t[:, 1] = 200:\n", t)
t[t > 10] = 20
print("t[t > 10] = 20\n", t)

t[0, 2]:
 tensor(3)
t[:, :2]:
 tensor([[1, 2],
        [4, 5]])
t[:, [1, 2]]:
 tensor([[2, 3],
        [5, 6]])
t[t > 3]:
 tensor([4, 5, 6])
t[0, 1] = 100:
 tensor([[  1, 100,   3],
        [  4,   5,   6]])
t[:, 1] = 200:
 tensor([[  1, 200,   3],
        [  4, 200,   6]])
t[t > 10] = 20
 tensor([[ 1, 20,  3],
        [ 4, 20,  6]])


In [49]:
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])

v2 = v + 10
print("v + 10:\n", v2)
v2 = v ** 2
print("v ** 2:\n", v2)
z = v - w
print("v - w:\n", z)
u = 2 * v - w / 10 + 6.0
print("2 * v - w / 10 + 6.0:\n", u)

print("m * 2.0:\n", m * 2.0)
print("m + v:\n", m + v)
print("m + m:\n", m + m)

v + 10:
 tensor([11., 12., 13.])
v ** 2:
 tensor([1., 4., 9.])
v - w:
 tensor([  1.,  -8., -17.])
2 * v - w / 10 + 6.0:
 tensor([ 8.,  9., 10.])
m * 2.0:
 tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
m + v:
 tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])
m + m:
 tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


In [90]:
X = torch.randn(2, 3)

print("X:\n", X)
print("X * 2 + torch.abs(X):\n", X * 2 + torch.abs(X))
print("torch.mean(X):\n", torch.mean(X))
m = X.mean()
print("m = X.mean():\n", m)
print("m.item():\n", m.item())
print("X.mean(0):\n", X.mean(0))

X:
 tensor([[ 1.4812,  0.7066, -0.2960],
        [ 0.3044,  0.4224,  0.3127]])
X * 2 + torch.abs(X):
 tensor([[ 4.4435,  2.1198, -0.2960],
        [ 0.9131,  1.2673,  0.9382]])
torch.mean(X):
 tensor(0.4886)
m = X.mean():
 tensor(0.4886)
m.item():
 0.4885588586330414
X.mean(0):
 tensor([0.8928, 0.5645, 0.0084])


In [113]:
x1 = torch.tensor([[1, 2], [3, 4.]])
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]])

print("x1.view(4, 1).shape: {}".format(x1.view(4, 1).shape))
print("x1.view(1, -1).shape: {}".format(x1.view(1, -1).size()))
print("x2.t().shape:{}".format(x2.t().shape))
print("torch.cat([x1, x2], dim=1).shape:{}".format(torch.cat([x1, x2], dim=1).shape))
hwc_img_data = torch.rand(100, 64, 32, 3)
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)
print("hwc_img_data.shape: {}\nchw_img_data.shape: {}".format(
    hwc_img_data.shape, chw_img_data.shape))

x1.view(4, 1).shape: torch.Size([4, 1])
x1.view(1, -1).shape: torch.Size([1, 4])
x2.t().shape:torch.Size([3, 2])
torch.cat([x1, x2], dim=1).shape:torch.Size([2, 5])
hwc_img_data.shape: torch.Size([100, 64, 32, 3])
chw_img_data.shape: torch.Size([100, 3, 64, 32])


In [125]:
m = torch.randn(100, 10)
v = torch.randn(10)

print("torch.dot(v, v).shape: {}".format(torch.dot(v, v).shape))
print("torch.mv(m, v).shape: {}".format(torch.mv(m, v).shape))
print("torch.mm(m.t(), m).shape: {}".format(torch.mm(m.t(), m).shape))
u, s, v = torch.svd(m)
print("u.shape:{}\ts.shape:{}\tv.shape:{}".format(u.shape, s.shape, v.shape))

torch.dot(v, v).shape: torch.Size([])
torch.mv(m, v).shape: torch.Size([100])
torch.mm(m.t(), m).shape: torch.Size([10, 10])
u.shape:torch.Size([100, 10])	s.shape:torch.Size([10])	v.shape:torch.Size([10, 10])


In [132]:
x = torch.randn(100, 3)

a = torch.tensor([1, 2, 3.], requires_grad=True)

y = torch.mv(x, a)
o = y.sum()

o.backward()

a.grad != x.sum(0)
print(a.grad)
print(x.sum(0))
print(x.grad)

tensor([  5.8587, -15.2160, -12.2551])
tensor([  5.8587, -15.2160, -12.2551])
None
